### ISSUE TITLE
Создать механизм установки cms

### ISSUE THREAD

**Issue by simple-man3** [reenekt/press-start-cms#28]
Есть два варианта установки cms:
1) У юзера есть уже готовая бд
2) У юзера нет готовой бд
--------------------------------------------------------------
В первом случае, нужно у него получить название бд, логин и пароль для доступа к ней
В втором случае, нужно попросить только логин и пароль и механизм сам создаст бд

**Comment by reenekt** [comment]
@simple-man3 бд должна создаваться отдельно и быть пустой на момент установки cms
даже в wordpress нужно использовать созданную БД

**Comment by reenekt** [comment]
\+ еще надо будет добавить файл, в котором будет прописано установлена ли CMS и может когда она была установлена.

---
Зачем это нужно:
* При первом входе в cms должно выходить окно установки.
* После установки такое окно не должно появляться никак.
* Значит что нужно проверять установлена ли cms или нет -> лучше всего сделать это через проверку наличия какого-то файла, например json файла с полем "установлена ли cms".
* После установки нужно изменять файл (значение в файле) чтобы указать что cms установлена.
