### ISSUE TITLE
Создать логику добавления новых полей ввода в контент

### ISSUE THREAD

**Issue by simple-man3** [reenekt/press-start-cms#29]
Сейчас есть только 2 ввода:
1) Название (title)
2) Содержимое (контент)
----------------------------------------------------------
Нужно создать логику таким образом, чтоб юзер мог добавлять новые поля ввода

**Comment by reenekt** [comment]
Предлагаю сделать через плагины
~а то нафиг я вообще вводил систему плагинов, если мы ее не используем~
это будет просто - сделать чтобы плагин добавлял нужные поля в интерфейс и хранить значения полей можно будет в БД в виде JSON строки.

Мы можем это согласовать, может я это сделаю, т к я разрабатывал систему плагинов и прекрасно знаю как она работает ~и что она пока не совсем адаптирована под работу с БД~

**Comment by reenekt** [comment]
[этот комментарий уже не актуален](https://github.com/reenekt/press-start-cms/issues/29#issuecomment-581002900) так как курсовой проект уже сдан.
хоть на мой взгляд разумнее было бы делать на плагинах, ты (@simple-man3) можешь делать как пожелаешь

**Comment by simple-man3** [comment]
хорошо, делай, но только обяъсни, как именно будешь делать, чтобы я имел общее представление, как это сделано.
Можно и не вдаваться в продробности
