### ISSUE TITLE
Доработка редактора записей

### ISSUE THREAD

**Issue by reenekt** [reenekt/press-start-cms#4]
нужно переработать редактор записей - разделить компонент редактора на 2 компонента:
1. компонент-редактор (только редактирование контента)
2. компонент для отображения (можно отображать и без компонента, но тогда стоит учесть стили, которые использует редактор, подробнее у @reenekt)

**Comment by simple-man3** [comment]
нужно подробнее на счёт этого обсудить

**Comment by reenekt** [comment]
@simple-man3 насчет этого: редактор записей у нас написан на vue, он находится в `resources/js/components/PostEditor.vue`.
1) сейчас у нас этот компонент используется и как редактор, и как компонент для отображения контента (там есть свойство readOnly на строке 241, оно и определяет возможность редактирования записи, нужно тупо скопировать файл .vue и в одном тупо убрать кнопки для редактирования/удаления записи, а в другом компоненте тупо убрать все проверки свойства readOnly, чтобы все кнопки редактирования всегда отображались)
2) для этих изменений нужен NPM... потому что после каждого изменения в `resources/js/components/PostEditor.vue` нужно пересобирать все js скрипты

в общем если задача кажется сложной - лучше напиши мне что не осиляешь ее и я сделаю ее как найду время

**Comment by simple-man3** [comment]
NPM что это?
