### ISSUE TITLE
Система тем

### ISSUE THREAD

**Issue by reenekt** [reenekt/press-start-cms#6]
Нужно продумать и разработать систему тем. Тему можно будет выбирать в панели администратора #3. В будущем можно будет скачивать их через "магазин плагинов и тем"

**Comment by simple-man3** [comment]
1 есть методы проверки существования view
2 используем json файлы для описаний тем

**Comment by reenekt** [comment]
> 1 есть методы проверки существования view
> 2 используем json файлы для описаний тем

1. в [руководстве](https://laravel.com/docs/6.x/views) есть подраздел **"Determining If A View Exists"**
2. нужно сделать класс, который загружал бы в себя данные из json файла и проводил валидацию структуры аналогично [этому классу](https://github.com/reenekt/press-start-cms/blob/master/app/Library/PluginSystem/PluginInfoScheme.php). 
Для загрузки тем нужно сделать отдельный Service Provider (также как и для плагинов, только кода будет меньше - https://github.com/reenekt/press-start-cms/blob/master/app/Providers/PluginServiceProvider.php)
по сути сам провайдер будет такой же, отличия будут после [этой строки](https://github.com/reenekt/press-start-cms/blob/be39b97b119f480572aeb4d8e2bd9ccf4253687a/app/Providers/PluginServiceProvider.php#L90) - там нужно будет вызывать метод `$this->loadViewsFrom($path, $namesoace)`. подробнее - https://laravel.com/docs/6.x/packages#views
